### PR TITLE
Add rubocop-capybara extension

### PR DESCRIPTION
**Pull request by pirj**
We've [extracted some cops](https://github.com/rubocop/rubocop-rspec/pull/1519) from [`rubocop-rspec`](https://github.com/rubocop/rubocop-rspec) to [`rubocop-capybara`](https://github.com/rubocop/rubocop-capybara).

Please accept my apologies for the lack of fundamental knowledge how docs.rubocop.org function. Please help me to shape this PR, and I'll be happy to send the next ones on my own, as we plan to extract `rubocop-factory_girl` and `rubocop-rspec-rails` in the near future.

When a new version of `rubocop-capybara` is released, will it automatically be published with those changes to https://docs.rubocop.org/rubocop-capybara?

### CODE REVIEW

**Comment by ydah** [comment]
@bbatsov , @koic sorry to bother you. May I ask you to check the PR here?

**Comment by koic** [comment]
> When a new version of rubocop-capybara is released, will it automatically be published with those changes to https://docs.rubocop.org/rubocop-capybara?

It is not automatically generated by release. This site will need to be rebuilt if the git tag is updated:
https://github.com/rubocop/docs.rubocop.org#building-the-site

Releases that do not require document updates do not require a rebuild.

> May I ask you to check the PR here?

Due to conflicts files, I will cherry-pick and generate the documentation this time.

**Comment by koic** [comment]
I will be closing this as it has been applied to the site.
https://docs.rubocop.org/rubocop-capybara/2.17/index.html

Thank you.

**Comment by ydah** [comment]
@koic Thank you. I appreciate it.

**Comment by pirj** [comment]
Thank you, @koic !

**Pull request closed without merging**
